name: Integration
on:
  push:
  schedule:
    - cron: "0 * * * *" # run once every hour

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Buildevents
        uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          job-status: ${{ job.status }}

      - run: |
          echo "STEP_ID=0" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID sleep -- sleep 5
      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'step 1'

      - run: |
          echo "STEP_ID=1" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID 'sleep some more' -- sleep 2
      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'step 2'
